import { AutomationRule, AutomationExecutionLog } from '@/types/automations';

export const INITIAL_AUTOMATION_RULES: AutomationRule[] = [
  {
    id: 'rule-kickoff',
    org_id: 'org-design-house',
    name: 'AEC Project Kickoff Pipeline',
    description: 'When a new commission is created, automatically provision CAD & BIM folder trees in Documents, ping HR with recommended architect assignments, and log compliance.',
    category: 'kickoff',
    enabled: true,
    triggerDomain: 'projects',
    triggerType: 'PROJECT_CREATED',
    triggerLabel: 'New Project Created',
    condition: {
      operator: 'always',
      label: 'Every project commission',
    },
    actions: [
      {
        id: 'act-doc-provision',
        domain: 'documents',
        actionType: 'DOCUMENTS_AUTO_PROVISION_FOLDERS',
        title: 'Provision CAD / BIM Folder Vault',
        description: 'Creates /projects/{name}/ with Blueprints & Specifications subfolders.',
      },
      {
        id: 'act-hr-suggest',
        domain: 'hr',
        actionType: 'HR_SUGGEST_ASSIGNMENT',
        title: 'Recommend Lead Architect',
        description: 'Evaluates architect skills matrix and recommends available staffing.',
      },
      {
        id: 'act-audit-kickoff',
        domain: 'platform',
        actionType: 'PLATFORM_CREATE_AUDIT_LOG',
        title: 'Immutable Compliance Audit',
        description: 'Logs commercial initialization with timestamp and user signature.',
      },
      {
        id: 'act-notif-kickoff',
        domain: 'platform',
        actionType: 'PLATFORM_SEND_NOTIFICATION',
        title: 'Broadcast Project Notification',
        description: 'Alerts project team with instant 1-click allocation link.',
      },
    ],
    executionCount: 14,
    lastExecutedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'rule-permit',
    org_id: 'org-design-house',
    name: 'Permit & Blueprint Auto-Review',
    description: 'When architectural CAD/DWG drawings are uploaded to Documents, automatically schedule a blueprint review milestone in Projects and assign a BIM specialist.',
    category: 'compliance',
    enabled: true,
    triggerDomain: 'documents',
    triggerType: 'DOCUMENT_UPLOADED',
    triggerLabel: 'CAD Drawing Uploaded',
    condition: {
      operator: 'contains',
      field: 'fileType',
      value: 'Drawing',
      label: 'File is CAD / DWG / Blueprint',
    },
    actions: [
      {
        id: 'act-milestone-permit',
        domain: 'projects',
        actionType: 'PROJECTS_ADD_MILESTONE',
        title: 'Schedule Code & Zoning Milestone',
        description: 'Adds "Blueprint Technical Audit & Permit Filing" to milestone tracker.',
      },
      {
        id: 'act-hr-bim',
        domain: 'hr',
        actionType: 'HR_SUGGEST_ASSIGNMENT',
        title: 'Assign BIM Specialist for Review',
        description: 'Allocates specialist to verify local architectural code compliance.',
      },
      {
        id: 'act-audit-permit',
        domain: 'platform',
        actionType: 'PLATFORM_CREATE_AUDIT_LOG',
        title: 'Log Drawing Version Lock',
        description: 'Records cryptographic revision checksum in platform audit trail.',
      },
    ],
    executionCount: 9,
    lastExecutedAt: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: 'rule-milestone',
    org_id: 'org-design-house',
    name: 'Milestone Handover & Archive Engine',
    description: 'When any project milestone reaches 100% completion, automatically archive deliverables into Documents and celebrate with team notification.',
    category: 'delivery',
    enabled: true,
    triggerDomain: 'projects',
    triggerType: 'MILESTONE_COMPLETED',
    triggerLabel: 'Milestone Status = Completed',
    condition: {
      operator: 'always',
      label: 'Any milestone completion',
    },
    actions: [
      {
        id: 'act-archive-doc',
        domain: 'documents',
        actionType: 'DOCUMENTS_ARCHIVE_MILESTONE',
        title: 'Provision As-Built Archive Folder',
        description: 'Creates /deliverables/as-builts/ for client sign-off records.',
      },
      {
        id: 'act-audit-milestone',
        domain: 'platform',
        actionType: 'PLATFORM_CREATE_AUDIT_LOG',
        title: 'Milestone Sign-Off Audit',
        description: 'Captures verifiable sign-off metadata in audit logs.',
      },
      {
        id: 'act-notif-milestone',
        domain: 'platform',
        actionType: 'PLATFORM_SEND_NOTIFICATION',
        title: 'Team Milestone Celebration',
        description: 'Broadcasts milestone success toast and updates project KPIs.',
      },
    ],
    executionCount: 22,
    lastExecutedAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'rule-high-budget',
    org_id: 'org-design-house',
    name: 'High-Value Commercial Governance Guard',
    description: 'Enforces executive oversight whenever a project budget exceeds $500,000 by requiring Principal Partner assignment and regulatory compliance logging.',
    category: 'compliance',
    enabled: true,
    triggerDomain: 'projects',
    triggerType: 'PROJECT_CREATED',
    triggerLabel: 'Project Budget > $500,000',
    condition: {
      operator: 'greater_than',
      field: 'budget',
      value: 500000,
      label: 'Budget > $500,000',
    },
    actions: [
      {
        id: 'act-hr-principal',
        domain: 'hr',
        actionType: 'HR_SUGGEST_ASSIGNMENT',
        title: 'Assign Principal Partner Oversight',
        description: 'Mandates executive review on major capital development.',
      },
      {
        id: 'act-audit-governance',
        domain: 'platform',
        actionType: 'PLATFORM_CREATE_AUDIT_LOG',
        title: 'Record Governance Checkpoint',
        description: 'Logs commercial escalation in enterprise audit logs.',
      },
    ],
    executionCount: 5,
    lastExecutedAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const INITIAL_EXECUTION_LOGS: AutomationExecutionLog[] = [
  {
    id: 'exec-1',
    ruleId: 'rule-kickoff',
    ruleName: 'AEC Project Kickoff Pipeline',
    triggerDomain: 'projects',
    triggerType: 'PROJECT_CREATED',
    status: 'success',
    latencyMs: 14,
    actionsTriggered: [
      'Auto-provisioned /projects/Skyline Luxury Tower/ folder in Documents',
      'Recommended Lead Architect in HR',
      'Logged project inception in Platform Audit Trail',
      'Broadcasted project creation alert',
    ],
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    summary: 'Commission "Skyline Luxury Tower" initiated; 4 cross-app actions executed in 14ms.',
  },
  {
    id: 'exec-2',
    ruleId: 'rule-milestone',
    ruleName: 'Milestone Handover & Archive Engine',
    triggerDomain: 'projects',
    triggerType: 'MILESTONE_COMPLETED',
    status: 'success',
    latencyMs: 9,
    actionsTriggered: [
      'Created /deliverables/as-builts/ in Documents',
      'Captured immutable milestone sign-off in Audit Trail',
      'Dispatched team notification',
    ],
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    summary: 'Milestone "Client Brief & Concept Sign-Off" completed; 3 cross-app actions executed.',
  },
  {
    id: 'exec-3',
    ruleId: 'rule-permit',
    ruleName: 'Permit & Blueprint Auto-Review',
    triggerDomain: 'documents',
    triggerType: 'DOCUMENT_UPLOADED',
    status: 'success',
    latencyMs: 18,
    actionsTriggered: [
      'Added "Blueprint Technical Audit" milestone to Projects',
      'Allocated BIM Specialist for review in HR',
      'Logged drawing checksum in Audit Trail',
    ],
    timestamp: new Date(Date.now() - 14400000).toISOString(),
    summary: 'Uploaded "Structural_Grid_Rev2.dwg"; scheduled review milestone & alerted BIM specialist.',
  },
  {
    id: 'exec-4',
    ruleId: 'rule-high-budget',
    ruleName: 'High-Value Commercial Governance Guard',
    triggerDomain: 'projects',
    triggerType: 'PROJECT_CREATED',
    status: 'filtered',
    latencyMs: 4,
    actionsTriggered: [],
    timestamp: new Date(Date.now() - 28800000).toISOString(),
    summary: 'Project budget ($280,000) did not meet $500,000 threshold. Pipeline filtered gracefully.',
  },
];
